---
all:
  children:
    linux:
      children:
        webserver:
          hosts:
            ansible01:
            ansible02:
        database:
          hosts:
            ansible03:
            ansible04:
        loadbalancer:
          hosts:
            ansible05:
            ansible06:
        webcluster-backend:
          hosts:
            webserver01:
            webserver02:
            webserver03:
        webcluster-loadbalancer:
          hosts:
            loadbalancer:
    windows:
      hosts:
      windows-server.ordix:
        ansible_connection: winrm
        ansible_user: ansible
        ansible_password: SeminarSetup2022
        ansible_winrm_server_cert_validation: ignore
